### ISSUE TITLE
Блок кода мешает навигации по архиву

### ISSUE THREAD

**Issue by inpos** [kodi-iptv-addons/kodi-iptv-addons#10]
https://github.com/kodi-iptv-addons/kodi-iptv-addons/blob/d7169ad8397f42e45ef7f8b9353dae29f821c6e0/script.module.iptvlib/lib/iptvlib/tvdialog.py#L362

Каждая команда навигации по архиву (перемотка, выбор записи из списка) вызывает появление диалога с сообщением "Выбранная программа не может быть воспроизведена". После нажатия ОК появляется список каналов.
При этом воспроизведение происходит.
Закомментировал данный блок кода и наслаждаюсь просмотром передач из архива.
Но, как я думаю, данный код нужен для обработки остановки воспроизведения. И, как мне кажется, необходимо обрабатывать навигацию по архиву и остановку воспроизведения верно.

Провайдер ТВ: itv.live
Плагин: ITV

**Comment by dmitry-vinogradov** [comment]
Можешь проверить существует ли описанная тобой проблема в новой версии приложения (1.1.2)

**Comment by dmitry-vinogradov** [comment]
close this due to no feedback
