### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by vlad-zeus** [kodi-iptv-addons/kodi-iptv-addons#11]
Добрый день.
При запуске вылетает ошибка 
Ошибка при выполении HTTP запроса:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

Win7 х86, Kodi 17.6
Версия OTTPlayer - последняя, из репозитария.

**Comment by vlad-zeus** [comment]
Лог:

15:24:59.882 T:5456  NOTICE: OTTPLAYER: Exception <class 'urllib2.URLError'>: message=
15:25:00.035 T:5456  NOTICE: OTTPLAYER: Exception <class 'iptvlib.api.ApiException'>: message=<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, code=1001

**Comment by dmitry-vinogradov** [comment]
Привет, можешь посмотреть используются ли в твоем плейлисте ссылки с протоколом https?

**Comment by vlad-zeus** [comment]
Нет, таких ссылок нет.

**Comment by vlad-zeus** [comment]
Сегодня заработал. 
Не знаю, что вчера было, переустановки/перезапуски коди и компа не помогали. похоже глюк со стороны серверов ottplayer
