### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_TLS'

### ISSUE THREAD

**Issue by ucon** [kodi-iptv-addons/kodi-iptv-addons#12]
На Kodi 17.6 выпадает сообщение "Произошла непредвиденная ошибка 'module' object has no attribute 'PROTOCOL_TLS'. Андроид 5.1.1

**Comment by dmitry-vinogradov** [comment]
Please check latest 1.1.8 release

**Comment by ucon** [comment]
I took it at https://raw.githubusercontent.com/kodi-iptv-addons/kodi-iptv-addons/master/repository.iptv.zip. Is it right?

**Comment by dmitry-vinogradov** [comment]
Если автообновление для дополнений установлено то обновление произойдет автоматически. В другом случае достаточно переустановить дополнение из репозитория. Указанная тобой ссылка верная.

**Comment by ucon** [comment]
Спасибо, после обновления заработало.
