### ISSUE TITLE
Pause

### ISSUE THREAD

**Issue by krentiken** [kodi-iptv-addons/kodi-iptv-addons#6]
Hi.
It would be great if could pause the viewing of programs.
You can implement such a functional?

**Comment by dmitry-vinogradov** [comment]
Actually, pause is a part of the default behaviour of the kodi player and should work in all addons as expected. If you have any problems with pause the video playback please provide following information:
* Addon name and version
* Kodi version and control type (TV remote, keyboard or maus etc.)
* Operating system

**Comment by krentiken** [comment]
Hi Dmitry!

Pause working:

- Ottclub latest version (1.1.1)
- kodi 18.0. Remote control - kore or G20 voice air remote
- osmc latest version on raspberry pi 3b+

Pause not working:
- Ottclub latest version (1.1.1)
- kodi 18.1. Remote control - kore or G20 voice air remote
- fedora 29 on Gigabyte KIT BRIX GB-BACE-3160

**Comment by krentiken** [comment]
It would be great if the opportunity to pause, stop, rewind, etc. was implemented in ottclub as in youtube.

<a href="https://ibb.co/5jghfGW"><img src="https://i.ibb.co/LgXd2Yz/IMG-20190317-122405.jpg" alt="IMG-20190317-122405" border="0"></a>
<a href="https://ibb.co/QYjfq7z"><img src="https://i.ibb.co/dkJr3s1/IMG-20190317-122315.jpg" alt="IMG-20190317-122315" border="0"></a><br />

**Comment by dmitry-vinogradov** [comment]
HI, just released ottclub 1.1.2 with fix for pause of the playback during archive playback. It seems like it's not possible to pause live broadcasting, I need to investigate more on this.

You can use Left / Right navigation buttons on your remote to jump back or forward during video playback.

**Comment by krentiken** [comment]
Hi
I can not update ottclub to version 1.1.2. latest available version 1.1.1

**Comment by dmitry-vinogradov** [comment]
Just go to  "My add-ons" -> "Install from repository" -> select "IPTV Add-ons repository" , in context menu (right click with mouse or longer hold OK on remote) select "Check for updates".  After that just got to Add-on information and update.

**Comment by krentiken** [comment]
Thanks, I updated. pause works on archive programs

**Comment by dmitry-vinogradov** [comment]
Were you able to move Backwards / Forwards during playback with Left / Right keys on remote as I mentioned above?

**Comment by krentiken** [comment]
The possibility of moving was in version 1.1.1. In version 1.1.2 there was a pause when viewing archival programs

**Comment by dmitry-vinogradov** [comment]
The initial problem with pause of playback is solved, so I will close this one.

**Comment by krentiken** [comment]
thank you Dmitry
