### ISSUE TITLE
Ottclub просмотр архива

### ISSUE THREAD

**Issue by krentiken** [kodi-iptv-addons/kodi-iptv-addons#8]
Дмитрий добрый день.
Буду писать по русски, поскольку аудитория как я понимаю русскоязычная. 
При использования вашего замечательного плагина столкнулся со следующей проблемой. Ottclub несколько месяцев назад увеличили возможность просмотра архива передач с 3 дней до 7 дней. Но я так понимаю в коде стоит ограничение в 3 дня, поскольку есть даже EPG за 7 дней и старше. Можете поправить. Спасибо!

**Comment by dmitry-vinogradov** [comment]
Привет, спасибо за информацию - исправлю в следующем релизе

**Comment by dmitry-vinogradov** [comment]
Fixed in release 1.1.3

**Comment by krentiken** [comment]
Спасибо!

**Comment by enkorsh** [comment]
Дмитрий, добрый день!
Посмотрите пожалуйста плагин, на ottclub перестал загружаться epg
[kodi.log](https://github.com/kodi-iptv-addons/kodi-iptv-addons/files/4318123/kodi.log)
Заранее спасибо!
