### ISSUE TITLE
stalker

### ISSUE THREAD

**Issue by aidarkz** [kodi-iptv-addons/kodi-iptv-addons#9]
Приветствую,
Хотел спросить насчёт Сталкера. Какого вида должен быть адрес портала для него. Ввожу свой
http://ottg.tv/stalker/c/index.html
Выдает ошибку
"Ошибка при выполнении запроса http"

**Comment by mifi1978** [comment]
> Приветствую, 
> Хотел спросить насчёт Сталкера. Какого рода должен быть адрес портала для него. Ввожу свой 
> http://ottg.tv/stalker/c/index.html
> Выдает ошибку 
> "Ошибка при выполнении запроса http"
поддерживаю

**Comment by dmitry-vinogradov** [comment]
Дополнение больше не поддерживается за отсутствием технической документации API v2
